import test from 'node:test';
import assert from 'node:assert/strict';
import {createGithubService,FRESH_MS,STALE_MS} from '../server/github.mjs';
function fixture(){let time=1800000000000;const entries=new Map(),calls=[];let upstream=null;const fetcher=async(url,opts)=>{calls.push({url,opts});if(upstream)return upstream(url);return Response.json(url.includes('/repos?')?[{name:'public',language:'TypeScript',private:false,stargazers_count:3},{name:'secret',private:true}]:{login:'octocat',type:'User',public_repos:2,name:'Octo',id:1,email:'unwanted@example.com'})};const service=createGithubService({cache:{get:async k=>entries.get(k),set:async(k,v)=>entries.set(k,v)},fetcher,now:()=>time});return {service,calls,entries,advance(ms){time+=ms},upstream(fn){upstream=fn},request(path='/api/github/octocat',token='test-server-only',ip='one'){return service(new Request('https://card.test'+path),{GITHUB_TOKEN:token},ip)}}}
test('uses a server token and only returns public fields; shared cache avoids repeated calls',async()=>{const f=fixture();const r=await f.request();assert.equal(r.status,200);const p=await r.json();assert.equal(p.repos.length,1);assert.equal(p.user.email,undefined);assert.equal(f.calls.length,6);assert.equal(f.calls[0].opts.headers.Authorization,'Bearer test-server-only');assert.ok(!JSON.stringify(p).includes('test-server-only'));const second=await(await f.request()).json();assert.equal(second.fromCache,true);assert.equal(f.calls.length,6)});
test('coalesces concurrent identical requests',async()=>{const f=fixture();await Promise.all(Array.from({length:10},()=>f.request()));assert.equal(f.calls.length,6)});
test('missing token never makes anonymous requests',async()=>{const f=fixture();assert.equal((await f.request(undefined,'')).status,503);assert.equal(f.calls.length,0)});
test('expired cache serves explicit stale data when GitHub throttles; cooldown prevents retry storms',async()=>{const f=fixture();await f.request();f.advance(FRESH_MS+1);f.upstream(()=>new Response('',{status:429,headers:{'Retry-After':'120'}}));const stale=await(await f.request()).json();assert.equal(stale.stale,true);const n=f.calls.length;assert.equal((await f.request('/api/github/other')).status,429);assert.equal(f.calls.length,n);f.advance(STALE_MS);assert.equal((await f.request()).status,429)});
test('404 invalidates old profile instead of resurrecting it',async()=>{const f=fixture();await f.request();f.advance(FRESH_MS+1);f.upstream(()=>new Response('',{status:404}));assert.equal((await f.request()).status,404);const n=f.calls.length;assert.equal((await f.request()).status,404);assert.equal(f.calls.length,n)});
test('rejects arbitrary paths and query parameters before upstream access',async()=>{const f=fixture();for(const path of ['/api/github/a--b','/api/github/-bad','/api/github/octocat?url=https://evil.test','/api/repos/private','/api/github/octocat/repos'])assert.equal((await f.request(path)).status,400);assert.equal(f.calls.length,0)});
test('invalid credentials never leak upstream error bodies',async()=>{const f=fixture();f.upstream(()=>new Response('secret token test-server-only',{status:401}));const r=await f.request();assert.equal(r.status,503);assert.ok(!(await r.text()).includes('test-server-only'))});
test('per-client throttling bounds unique uncached requests',async()=>{const f=fixture();for(let i=0;i<20;i++)assert.equal((await f.request('/api/github/user'+i)).status,200);assert.equal((await f.request('/api/github/last')).status,429);assert.equal((await f.request('/api/github/user0')).status,200)});
