# Generated by Django 5.2.17 on 2026-09-15 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=39, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("avatar", models.URLField(blank=True)),
                ("timezone", models.CharField(default="UTC", max_length=80)),
                ("joined", models.BigIntegerField()),
                ("access_token", models.TextField(blank=True)),
                ("card", models.JSONField(blank=True, null=True)),
                ("published", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OAuthState",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("verifier", models.TextField()),
                ("expires", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField()),
                ("saved", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="workspace.userprofile",
                    ),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("body", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("token", models.TextField()),
                ("expires", models.BigIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkSession",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("started", models.BigIntegerField()),
                ("ended", models.BigIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.userprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended__isnull", True)),
                        fields=("user",),
                        name="one_active_work_session",
                    )
                ],
            },
        ),
    ]
