# Generated by Django 5.2.17 on 2026-10-04 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_profile_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDraft',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='workspace.userprofile')),
                ('value', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='worksession',
            name='project',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('created', models.BigIntegerField()),
                ('updated', models.BigIntegerField()),
                ('error', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('image', models.BinaryField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CardRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('value', models.JSONField(default=dict)),
                ('created', models.BigIntegerField()),
                ('restored_from', models.PositiveIntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.BigIntegerField()),
                ('actor', models.CharField(max_length=150)),
                ('note', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.backgroundjob')),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched', models.BigIntegerField(null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workspace.backgroundjob')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('minutes', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=30)),
                ('day', models.DateField()),
                ('value', models.JSONField()),
                ('captured', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.userprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'period', 'day'), name='daily_activity_snapshot')],
            },
        ),
        migrations.AddConstraint(
            model_name='backgroundjob',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['pending', 'running', 'unknown'])), fields=('user', 'kind'), name='one_active_background_job'),
        ),
        migrations.AddConstraint(
            model_name='cardrevision',
            constraint=models.UniqueConstraint(fields=('user', 'number'), name='card_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='weeklygoal',
            constraint=models.UniqueConstraint(fields=('user', 'week'), name='one_weekly_goal'),
        ),
    ]
